export const projects = [
  {
    id: "arthix",
    title: "Arthix v2",
    subtitle: "Financial Simulation Platform",
    description: "A full-scale financial simulation and portfolio management platform with real-time market data, algorithmic trading strategies, and advanced risk analytics.",
    tech: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    image: "/projects/arthix.png",
    link: "#",
    color: "#8B5CF6",
    year: "2024",
  },
  {
    id: "ledzer",
    title: "Ledzer",
    subtitle: "Intelligent Accounting System",
    description: "Business-grade ledger accounting platform with automated reconciliation, multi-currency support, and intelligent categorization powered by ML.",
    tech: ["React", "Node.js", "PostgreSQL", "GraphQL"],
    image: "/projects/ledzer.png",
    link: "#",
    color: "#3B82F6",
    year: "2024",
  },
  {
    id: "voughtmart",
    title: "VoughtMart",
    subtitle: "E-Commerce Experience",
    description: "Immersive digital marketplace with 3D product previews, advanced filtering, Stripe payment integration, and real-time inventory management.",
    tech: ["Next.js", "Framer Motion", "Stripe", "Tailwind"],
    image: "/projects/voughtmart.png",
    link: "#",
    color: "#10B981",
    year: "2023",
  },
  {
    id: "eternite",
    title: "Éternité",
    subtitle: "Luxury Brand Platform",
    description: "Premium digital experience for a luxury fashion brand featuring WebGL product showcases, scroll-driven storytelling, and cinematic transitions.",
    tech: ["WebGL", "Three.js", "GSAP", "Next.js"],
    image: "/projects/eternite.png",
    link: "#",
    color: "#D4AF37",
    year: "2023",
  },
  {
    id: "swasthsathi",
    title: "SwasthSathi",
    subtitle: "Health-Tech Solution",
    description: "Accessible healthcare platform connecting patients with medical resources, featuring telemedicine integration and health record management.",
    tech: ["React Native", "Firebase", "Redux", "Node.js"],
    image: "/projects/swasthsathi.png",
    link: "#",
    color: "#EF4444",
    year: "2023",
  },
  {
    id: "portfolio-v1",
    title: "Portfolio v1",
    subtitle: "Personal Brand Site",
    description: "The first iteration of my personal portfolio — a minimalist design exercise that taught me the fundamentals of web animation and storytelling.",
    tech: ["React", "Framer Motion", "Tailwind"],
    image: "/projects/portfolio.png",
    link: "#",
    color: "#6366F1",
    year: "2022",
  },
];
