export const projects = [
  {
    id: "arthix",
    title: "ArthiX",
    subtitle: "Domain Ecosystem",
    description: "An AI-accelerated Neural Terminal designed to bridge India's financial literacy gap through immersive simulation, risk-free practice, and a deep-data ledger.",
    tech: ["Next.js", "Framer Motion", "Firebase", "Tailwind"],
    image: "/projects/arthix.png",
    link: "https://arthix.in",
    color: "#8B5CF6",
    year: "2026",
  },
  {
    id: "ledzer",
    title: "Ledzer",
    subtitle: "Modern Business OS",
    description: "A full-stack business platform built for speed and real-world usability. Handles invoicing, inventory, accounting workflows, offline support, and exports.",
    tech: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind"],
    image: "/projects/ledzer.png",
    link: "https://ledzer.vercel.app",
    color: "#3B82F6",
    year: "2026",
  },
  {
    id: "voughtmart",
    title: "VoughtMart",
    subtitle: "Superhero E-Commerce",
    description: "A dark, brutal, and smooth e-commerce interface featuring 60FPS animations, Homelander laser effects, and custom Canvas-based interactions.",
    tech: ["React 18", "Tailwind CSS v4", "Framer Motion", "Canvas API"],
    image: "/projects/voughtmart.png",
    link: "https://lnkd.in/g56RBFTn",
    color: "#10B981",
    year: "2026",
  },
  {
    id: "eternite",
    title: "Éternité",
    subtitle: "Luxury Fragrance Store",
    description: "A fully responsive, high-end luxury e-commerce concept. Built using AI orchestration for complex feature integration and custom photorealistic assets.",
    tech: ["Next.js", "AI Orchestration", "Design"],
    image: "/projects/eternite.png",
    link: "https://lnkd.in/gTDdHsGV",
    color: "#D4AF37",
    year: "2025",
  },
  {
    id: "swasthsathi",
    title: "SwasthSathi",
    subtitle: "Telehealth Solution",
    description: "A healthcare platform focusing on user experience and accessible telehealth solutions, marking the start of my hands-on product management journey.",
    tech: ["UX Design", "Project Management"],
    image: "/projects/swasthsathi.png",
    link: "#",
    color: "#EF4444",
    year: "2025",
  },
];
